### ISSUE TITLE
TypeError: Cannot read property 'destroy' of null

### ISSUE THREAD

**Issue by fengzstrong** [tcncloud/agi-node#3]
If i put 'channel' to a function, an error occurred.

function testScript(channel) {
  console.log('Script got call %s -> %s', channel.request.callerid, channel.request.extension);
  var test = function() {
    channel.exec("Dial", "PJSIP/6999,10");
    console.log('res', res);
  };
  test();
}

![image](https://cloud.githubusercontent.com/assets/11294465/20375279/2b49c32e-acb9-11e6-8522-34d57e57bb41.png)

**Comment by sigxcpu76** [comment]
Can you post the whole code? 
If you replace `exec()` with something else does it work (pick `answer()` for example)?

**Comment by merajmehrabi** [comment]
Any update?

**Comment by sigxcpu76** [comment]
See the above comment.

**Comment by JulianGerhard** [comment]
Hi,

the script works as expected, but how can i decide, which function inside to call? Example:

I've got the extension calls:

exten => 1234,n,agi(agi://127.0.0.1/submitgs);
exten => 1234,n,agi(agi://127.0.0.1/receivetts);

And now I want the node.js - File to listen on port 4573 and execute either function submitgs or receivetts - but how? 

If I write: 

var server = new AGIServer(script, 4573);

script isnt found and if I write one of the functions, only this one is executed?

Thank you for your help!

**Comment by namtzigla** [comment]
This is a stalled issue, I'm going to close it!

**Comment by oscarrock** [comment]
I have a question here too. When call is connected trough agi server but user hangs up then ocurrs an exception as shown below. I asume this is because thread is being disconnected in unexpected way. 

Is there any workaround to properly catch this events so the extensión can continue its normal execution? Thank you by the way this agi-node library its working very well.

`
TypeError: Cannot read property 'destroy' of null
1|Gateway  |     at AGIChannel.<anonymous> (/home/mserver/node_modules/agi-node/lib/agi-server.js:55:19)
1|Gateway  |     at emitNone (events.js:106:13)
1|Gateway  |     at AGIChannel.emit (events.js:208:7)
1|Gateway  |     at /home/mserver/node_modules/agi-node/lib/agi-channel.js:76:12
`
